AllCops:
  NewCops: enable
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
Metrics/BlockLength:
  Enabled: false
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
